log_file_path: "/opt/cowrie/var/log/cowrie/cowrie.log"

abuseipdb:
  api_key: "Your_AbuseIPDB_API_Key"

email:
  smtp_server: "smtp.gmail.com"
  smtp_port: 587
  sender_email: "Your_email"
  sender_password: "Your password"
  recipient_email: "The mail which you wanna sent email to"



